# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footballers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=25, null=True)),
                ('nationality', models.CharField(blank=True, db_column='Nationality', max_length=19, null=True)),
                ('national_position', models.CharField(blank=True, db_column='National_Position', max_length=3, null=True)),
                ('national_kit', models.CharField(blank=True, db_column='National_Kit', max_length=2, null=True)),
                ('club', models.CharField(blank=True, db_column='Club', max_length=17, null=True)),
                ('club_position', models.CharField(blank=True, db_column='Club_Position', max_length=3, null=True)),
                ('club_kit', models.CharField(blank=True, db_column='Club_Kit', max_length=2, null=True)),
                ('club_joining', models.CharField(blank=True, db_column='Club_Joining', max_length=10, null=True)),
                ('contract_expiry', models.CharField(blank=True, db_column='Contract_Expiry', max_length=4, null=True)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
                ('height', models.CharField(blank=True, db_column='Height', max_length=6, null=True)),
                ('weight', models.CharField(blank=True, db_column='Weight', max_length=5, null=True)),
                ('preffered_foot', models.CharField(blank=True, db_column='Preffered_Foot', max_length=5, null=True)),
                ('birth_date', models.CharField(blank=True, db_column='Birth_Date', max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('preffered_position', models.CharField(blank=True, db_column='Preffered_Position', max_length=9, null=True)),
                ('work_rate', models.CharField(blank=True, db_column='Work_Rate', max_length=15, null=True)),
                ('weak_foot', models.IntegerField(blank=True, db_column='Weak_foot', null=True)),
                ('skill_moves', models.IntegerField(blank=True, db_column='Skill_Moves', null=True)),
                ('ball_control', models.IntegerField(blank=True, db_column='Ball_Control', null=True)),
                ('dribbling', models.IntegerField(blank=True, db_column='Dribbling', null=True)),
                ('marking', models.IntegerField(blank=True, db_column='Marking', null=True)),
                ('sliding_tackle', models.IntegerField(blank=True, db_column='Sliding_Tackle', null=True)),
                ('standing_tackle', models.IntegerField(blank=True, db_column='Standing_Tackle', null=True)),
                ('aggression', models.IntegerField(blank=True, db_column='Aggression', null=True)),
                ('reactions', models.IntegerField(blank=True, db_column='Reactions', null=True)),
                ('attacking_position', models.IntegerField(blank=True, db_column='Attacking_Position', null=True)),
                ('interceptions', models.IntegerField(blank=True, db_column='Interceptions', null=True)),
                ('vision', models.IntegerField(blank=True, db_column='Vision', null=True)),
                ('composure', models.IntegerField(blank=True, db_column='Composure', null=True)),
                ('crossing', models.IntegerField(blank=True, db_column='Crossing', null=True)),
                ('short_pass', models.IntegerField(blank=True, db_column='Short_Pass', null=True)),
                ('long_pass', models.IntegerField(blank=True, db_column='Long_Pass', null=True)),
                ('acceleration', models.IntegerField(blank=True, db_column='Acceleration', null=True)),
                ('speed', models.IntegerField(blank=True, db_column='Speed', null=True)),
                ('stamina', models.IntegerField(blank=True, db_column='Stamina', null=True)),
                ('strength', models.IntegerField(blank=True, db_column='Strength', null=True)),
                ('balance', models.IntegerField(blank=True, db_column='Balance', null=True)),
                ('agility', models.IntegerField(blank=True, db_column='Agility', null=True)),
                ('jumping', models.IntegerField(blank=True, db_column='Jumping', null=True)),
                ('heading', models.IntegerField(blank=True, db_column='Heading', null=True)),
                ('shot_power', models.IntegerField(blank=True, db_column='Shot_Power', null=True)),
                ('finishing', models.IntegerField(blank=True, db_column='Finishing', null=True)),
                ('long_shots', models.IntegerField(blank=True, db_column='Long_Shots', null=True)),
                ('curve', models.IntegerField(blank=True, db_column='Curve', null=True)),
                ('freekick_accuracy', models.IntegerField(blank=True, db_column='Freekick_Accuracy', null=True)),
                ('penalties', models.IntegerField(blank=True, db_column='Penalties', null=True)),
                ('volleys', models.IntegerField(blank=True, db_column='Volleys', null=True)),
                ('gk_positioning', models.IntegerField(blank=True, db_column='GK_Positioning', null=True)),
                ('gk_diving', models.IntegerField(blank=True, db_column='GK_Diving', null=True)),
                ('gk_kicking', models.IntegerField(blank=True, db_column='GK_Kicking', null=True)),
                ('gk_handling', models.IntegerField(blank=True, db_column='GK_Handling', null=True)),
                ('gk_reflexes', models.IntegerField(blank=True, db_column='GK_Reflexes', null=True)),
            ],
            options={
                'db_table': 'footballers',
                'managed': False,
            },
        ),
    ]
