# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=25, null=True)),
                ('nationality', models.CharField(blank=True, db_column='nationality', max_length=19, null=True)),
                ('national_position', models.CharField(blank=True, db_column='national_position', max_length=3, null=True)),
                ('national_kit', models.CharField(blank=True, db_column='national_kit', max_length=2, null=True)),
                ('club', models.CharField(blank=True, db_column='club', max_length=17, null=True)),
                ('club_position', models.CharField(blank=True, db_column='club_position', max_length=3, null=True)),
                ('club_kit', models.CharField(blank=True, db_column='club_kit', max_length=2, null=True)),
                ('club_joining', models.CharField(blank=True, db_column='club_joining', max_length=10, null=True)),
                ('contract_expiry', models.CharField(blank=True, db_column='contract_expiry', max_length=4, null=True)),
                ('rating', models.IntegerField(blank=True, db_column='rating', null=True)),
                ('height', models.CharField(blank=True, db_column='height', max_length=6, null=True)),
                ('weight', models.CharField(blank=True, db_column='weight', max_length=5, null=True)),
                ('preffered_foot', models.CharField(blank=True, db_column='preffered_foot', max_length=5, null=True)),
                ('birth_date', models.CharField(blank=True, db_column='birth_date', max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, db_column='age', null=True)),
                ('preffered_position', models.CharField(blank=True, db_column='preffered_position', max_length=9, null=True)),
                ('work_rate', models.CharField(blank=True, db_column='work_rate', max_length=15, null=True)),
                ('weak_foot', models.IntegerField(blank=True, db_column='weak_foot', null=True)),
                ('skill_moves', models.IntegerField(blank=True, db_column='skill_moves', null=True)),
                ('ball_control', models.IntegerField(blank=True, db_column='ball_control', null=True)),
                ('dribbling', models.IntegerField(blank=True, db_column='dribbling', null=True)),
                ('marking', models.IntegerField(blank=True, db_column='marking', null=True)),
                ('sliding_tackle', models.IntegerField(blank=True, db_column='sliding_tackle', null=True)),
                ('standing_tackle', models.IntegerField(blank=True, db_column='standing_tackle', null=True)),
                ('aggression', models.IntegerField(blank=True, db_column='aggression', null=True)),
                ('reactions', models.IntegerField(blank=True, db_column='reactions', null=True)),
                ('attacking_position', models.IntegerField(blank=True, db_column='attacking_position', null=True)),
                ('interceptions', models.IntegerField(blank=True, db_column='interceptions', null=True)),
                ('vision', models.IntegerField(blank=True, db_column='vision', null=True)),
                ('composure', models.IntegerField(blank=True, db_column='composure', null=True)),
                ('crossing', models.IntegerField(blank=True, db_column='crossing', null=True)),
                ('short_pass', models.IntegerField(blank=True, db_column='short_pass', null=True)),
                ('long_pass', models.IntegerField(blank=True, db_column='long_pass', null=True)),
                ('acceleration', models.IntegerField(blank=True, db_column='acceleration', null=True)),
                ('speed', models.IntegerField(blank=True, db_column='speed', null=True)),
                ('stamina', models.IntegerField(blank=True, db_column='stamina', null=True)),
                ('strength', models.IntegerField(blank=True, db_column='strength', null=True)),
                ('balance', models.IntegerField(blank=True, db_column='balance', null=True)),
                ('agility', models.IntegerField(blank=True, db_column='agility', null=True)),
                ('jumping', models.IntegerField(blank=True, db_column='jumping', null=True)),
                ('heading', models.IntegerField(blank=True, db_column='heading', null=True)),
                ('shot_power', models.IntegerField(blank=True, db_column='shot_power', null=True)),
                ('finishing', models.IntegerField(blank=True, db_column='finishing', null=True)),
                ('long_shots', models.IntegerField(blank=True, db_column='long_shots', null=True)),
                ('curve', models.IntegerField(blank=True, db_column='curve', null=True)),
                ('freekick_accuracy', models.IntegerField(blank=True, db_column='freekick_accuracy', null=True)),
                ('penalties', models.IntegerField(blank=True, db_column='penalties', null=True)),
                ('volleys', models.IntegerField(blank=True, db_column='volleys', null=True)),
                ('gk_positioning', models.IntegerField(blank=True, db_column='gk_positioning', null=True)),
                ('gk_diving', models.IntegerField(blank=True, db_column='gk_diving', null=True)),
                ('gk_kicking', models.IntegerField(blank=True, db_column='gk_kicking', null=True)),
                ('gk_handling', models.IntegerField(blank=True, db_column='gk_handling', null=True)),
                ('gk_reflexes', models.IntegerField(blank=True, db_column='gk_reflexes', null=True)),
            ],
            options={
                'db_table': 'footballers',
                'managed': False,
            },
        ),
    ]
